#version of docker compose
version: '3.9'

#main block of services
services:
  #app service
  app:
    #build
    build:
      #context: currentDirectory
      context: .
    #map 8000 of system to 8000 port of docker image
    ports:
      - '8000:8000'
    #mapping app directory
    volumes:
      - ./app:/app
    #default command when we run docker compose run
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
