#version of docker compose
version: '3.9'

#main block of services
services:
  #app service
  app:
    #build
    build:
      #context: currentDirectory
      context: .
      #for dev environment
      args:
        - DEV=true
    #map 8000 of system to 8000 port of docker image
    ports:
      - '8000:8000'
    #mapping app directory
    volumes:
      - ./app:/app
    #default command when we run docker compose run
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
  #Database service
  db:
    image: postgres:13-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
